vich_uploader:
    db_driver: orm

    mappings:
        products:
            inject_on_load: true
            uri_prefix: /image/imageUpLoader
            upload_destination: '%kernel.project_dir%/public/image/imageUpLoader'
#            namer : Vich\UploaderBundle\Naming\SmartUniqueNamer


